name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  another_flushbar: ^1.12.30
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

  # New architecture dependencies
  get_it: ^7.6.7
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
